# Generated by Django 5.2.8 on 2025-11-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discountedd_price',
            new_name='discounted_price',
        ),
    ]
