# Generated by Django 5.2.8 on 2025-12-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_discountedd_price_product_discounted_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=150)),
            ],
        ),
    ]
